
%% Add paths
addpath(genpath('Y:\LabMembers\MTillman\MATLAB_FileExchange_Repository'));

%% Load config
configPath = 'config.toml';
config = toml.map_to_struct(toml.read(configPath));

%% Dataset setup
data_root = config.paths.data_root;
schema = config.schema;
scidb.configure_database("test.db", fieldnames(schema), "pipeline.db");

%% Path inputs (shared templates)
rc_metrics_path = scidb.PathInput( ...
    "{subject}/{subject}_{device}_TEPS_LE/{subject}_{device}_TEPS_LE_recruitment_curves.csv", ...
    root_folder=data_root);

per_pulse_path = scidb.PathInput( ...
    "{subject}/{subject}_{device}_TEPS_LE/{subject}_{device}_TEPS_LE_per_pulse_metrics.csv", ...
    root_folder=data_root);

%% Number of muscles showing RMT
scidb.for_each(@countMusclesRMT, ...
    struct('rcMetricsPath', rc_metrics_path), ...
    {NumMusclesRMT()}, ...
    subject=schema.subject, ...
    device=schema.device);

%% Lowest RMT value
scidb.for_each(@computeLowestRMT, ...
    struct('rcMetricsPath', rc_metrics_path), ...
    {LowestRMT()}, ...
    subject=schema.subject, ...
    device=schema.device);

%% Tolerance
scidb.for_each(@computeTolerance, ...
    struct('perPulseMetricsPath', per_pulse_path), ...
    {Tolerance()}, ...
    subject=schema.subject, ...
    device=schema.device);